language: android

android:
  components:
    - tools
    - platform-tools
    - tools
    
    - build-tools-19.1.0
    - build-tools-26.0.1

    # The SDK version used to compile your project
    - android-26

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # System images for emulation
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-17
